### ISSUE TITLE
GAFT问题回复

### ISSUE THREAD

**Issue by gongyongq** [zsluedem/MonkTrader#112]
GAFT这个框架好Low，功能单一，速度还贼慢，远远不及pymoo等权威框架。我折腾了很久，弃坑了。说多了都是泪啊。

**Comment by zsluedem** [comment]
它其实没有并行，而且全部python当然慢啦。。我不用了。。

**Comment by zsluedem** [comment]
@gongyongq 吐槽吐到这里，也是牛逼，没什么特别得我就close了
